import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Data from '../components/list'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/dglubokov">GitHub</a>
        </h1>

        <Data/>

      </main>

      <footer className={styles.footer}>
        GitHub
      </footer>
    </div>
  )
}
